name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JacobBumgarner
body:
  - type: markdown
    attributes: 
      value: |
        Thanks for exploring VesselVio and taking the time to file a bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, please tell us how to replicate this bug.
      placeholder: Tell us what you see!
      value: "I found a bug!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
