name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JacobBumgarner
body:
  - type: markdown
    attributes: 
      value: |
        Thanks for exploring VesselVio and taking the time to file a bug report!
  

