blank_issues_enabled: True
contact_links:
  - name: VesselVio Discussion
    url: https://github.com/JacobBumgarner/VesselVio/discussions
    about: Please ask and answer questions here.
  - name: VesselVio Slack Community
    url: https://communityinviter.com/apps/vesselvio/join-vesselvio-on-slack
    about: The best place to receive quick communication and troubleshooting tips.
