blank_issues_enabled: True
contact_links:
  - name: VesselVio Slack Community
    url: https://communityinviter.com/apps/vesselvio/join-vesselvio-on-slack
    about: Please ask and answer questions here.
